### ISSUE TITLE
Logging Interface

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/typhon#16]
## Expected Behavior

Create a standard widget to display log stream. This could ideally be configured to go to the terminal, display in the widget or write to disk. The user should also have the option to change the logging configuration from within the UI itself. 

## Possible Solution

Ideally this is just a drop down menu standard on all screens. This might even be worth a PR directly into PyDM? This way it could be a menu item on the PyDMMainWindow

**Comment by hhslepicka** [comment]
:+1: to this idea!

**Comment by teddyrendahl** [comment]
@hhslepicka Think it belongs in PyDM or here?

**Comment by hhslepicka** [comment]
I would like to see this as a common widget at PyDM.
