### ISSUE TITLE
Alternative TyphonDeviceDisplay states

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/typhon#160]
Currently, `typhon` has an Enum to control which kind of display you want:

```python
class DisplayTypes:
    """Types of Available Templates"""
    embedded_screen = 0
    detailed_screen = 1
    engineering_screen = 2
```

What do you think about removing this and just having a boolean property `embedded`. I'm not sure that `engineering_screen` is that necessary. The real benefit is seen in the `QSS` when this:

```
TyphonDeviceDisplay[display_type='0'] {...}
TyphonDeviceDisplay[display_type='1'] {...}
TyphonDeviceDisplay[display_type='2'] {...}
```
becomes
```
TyphonDeviceDisplay {}
TyphonDeviceDisplay[embedded='True']{}
```
We do lose some specificity though....

**Comment by ZLLentz** [comment]
Is the claim here that we'll never want the "all signals" engineering screen? Or that we'll never want the "some signals" screen?

**Comment by klauer** [comment]
I like that it makes the QSS easier, but I think designing around its flaws is probably the opposite direction that we should be taking:
1. Implement cool and useful things
2. Do our best to get the QSS to work with it

Random thought - what if we preprocess the style sheet file such that we can add in some features that we really want? It would be easy to add in actual enum strings, though less easy to come up with a way to handle the class hierarchy issues.
