### ISSUE TITLE
Issues with Precision

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/typhon#205]
## Expected Behavior

Auto-precision for signals should follow the PV's precision always

## Current Behavior

After the first update, the PV's precision is dropped and becomes zero

## Possible Solution

My kluge is a bit suggestive, extra lines to `typhon/signal.py`:
```
try:
    widget_instance.precisionFromPV = False
    widget_instance.precision = signal.precision
except AttributeError:
    pass
```
e.g. this could be a `pydm` problem but I can't really tell

## Steps to Reproduce (for bugs)

1. Create a typhon screen from an EpicsMotor with a real IOC
2. Move the motor and watch the precision of the readback

## Context

We need more digits!!!

## Your Environment

Standard pcds conda, version 2.1.1

**Comment by hhslepicka** [comment]
@ZLLentz do you mind to provide me one example of PV so I can reproduce this case with PyDM and also what is the output and the expected output? 
Another question is: which version of PyDM are you using?

**Comment by ZLLentz** [comment]
`TST:PPM:MMS:Y.RBV` is my current PV. I think we're a few versions back in pydm (`1.6.5`), I should definitely update and try again.

**Comment by teddyrendahl** [comment]
Confirmed that `ophyd` is seeing the precision correctly

```
{'readback': {'source': 'PV:TST:PPM:MMS:Y.RBV',
  'dtype': 'number',
  'shape': [],
  'precision': 3,
  'units': 'mm',
  'lower_ctrl_limit': -4.0,
  'upper_ctrl_limit': 104.0}}
```

**Comment by ZLLentz** [comment]
I see the same issue when switching to `pydm` latest, but only on the `.RBV` PV. The setpoints, limit positions, etc. all have the correct precisions.

**Comment by hhslepicka** [comment]
I will investigate it here... sorry about that!

**Comment by teddyrendahl** [comment]
I do believe that this test should cover the `typhon` side

**Comment by ZLLentz** [comment]
Note that the widget originally comes up with the correct precision, but after the epics monitor update the precision is dropped.

**Comment by hhslepicka** [comment]
Please give it a try with: `/reg/neh/home/slepicka/test_pydm/precision.ui`

**Comment by teddyrendahl** [comment]
Further debugging reveals that this is only an issue through the gateway which leads me to determine this an issue with a lower level detail of the EPICS communication.
