### ISSUE TITLE
Add More Default Macros

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/typhon#207]
## Expected Behavior

It should be easy to extend the default typhon screens for custom applications without writing custom code to load them.

## Current Behavior

Only the "name" attribute is applied by default when loading the templates, so if you want to add other stuff from the device e.g. specific PVs in pydm widgets you have to manually add macros for prefix, etc., making the whole process feel less automatic. See my code:
```
import os.path

from pcdsdevices.epics_motor import BeckhoffAxis
from qtpy.QtWidgets import QApplication
import typhon

motor = BeckhoffAxis('TST:PPM:MMS:Y', name='test_ppm')
macros = {'name': motor.name,
          'prefix': motor.prefix}

app = QApplication([])
typhon.use_stylesheet()
dirname, _ = os.path.split(os.path.abspath(__file__))
template = dirname + '/detailed_beckhoff_motor.ui'
suite = typhon.TyphonSuite.from_device(motor)
suite.get_subdisplay(motor).load_template(macros=macros)
suite.get_subdisplay(motor).force_template = template
suite.show()
app.exec_()
```

## Possible Solution

Add other attributes to the default macros list, such as prefix. Admittedly I can't think of any other candidates, but hopefully others have ideas.

**Comment by teddyrendahl** [comment]
If you load your device from `happi`, all of the metadata will be added as macros
https://github.com/pcdshub/typhon/blob/3dc01d880f52531a51cf00d02f96ae716dbed3c8/typhon/display.py#L204
That being said, the `prefix` is a very quick and obvious check. It was excluded originally because they aren't attached to the `ophyd.sim` objects I test with, but that is a poor reason!

**Comment by ZLLentz** [comment]
Ahh, another strike against me for not using happi! I should have learned my lesson by now and made a tiny test device database.

**Comment by teddyrendahl** [comment]
I think `typhon` still has the written goal of being fully featured without `happi`. I appreciate the testing cycles
